---
- name: Generate password
  hosts: localhost
  tasks:

  # change psecret_password for password
    - name: Generate password
      ansible.builtin.debug:
        msg: "{{ 'secret_password' | password_hash('sha512') }}"
